var mm='<dl id="MegaMenu">';
mm += '<dt class="MMGlobalNaviStyle"><a href="$link$">Section 1</a></dt>';
mm += '<dd class="MMSet">';
mm += '<div class="MMColumnArea">';
mm += '<div class="MMGrid1 MMFirstItem">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '</div><!--/MMColumnArea-->';
mm += '</dd><!--/MMSet-->';
mm += '<dt class="MMGlobalNaviStyle"><a href="$link$">Section 2</a></dt>';
mm += '<dd class="MMSet">';
mm += '<div class="MMColumnArea">';
mm += '<div class="MMGrid1 MMFirstItem">';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '</div><!--/MMColumnArea-->';
mm += '</dd><!--/MMSet-->';
mm += '<dt class="MMGlobalNaviStyle"><a href="$link$">Section 3</a></dt>';
mm += '<dd class="MMSet">';
mm += '<div class="MMColumnArea">';
mm += '<div class="MMGrid1 MMFirstItem">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<ul class="MMLinkListStyle">';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '<li><a href="$Link$">[Link List]</a></li>';
mm += '</ul>';
mm += '</div><!--/MMGrid1-->';
mm += '<div class="MMGrid1">';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '</div><!--/MMGrid1-->';
mm += '</div><!--/MMColumnArea-->';
mm += '</dd><!--/MMSet-->';
mm += '<dt class="MMGlobalNaviStyle"><a href="$link$">Section 4</a></dt>';
mm += '<dd class="MMSet">';
mm += '<div class="MMColumnArea">';
mm += '<div class="MMGrid4 MMFirstItem">';
mm += '<div class="MMColumn1 MMFirstItem">';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '</div><!--/MMColumn1-->';
mm += '<div class="MMColumn1">';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '</div><!--/MMColumn1-->';
mm += '<div class="MMColumn1">';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '</div><!--/MMColumn1-->';
mm += '<div class="MMColumn1">';
mm += '<p class="MMBannerLinkStyle"><a href="$Link$"><img src="/image/en/dummy/dummy_300x130.gif" width="300" height="130" alt="Alternative Text" /><strong><span>Banner module (p)</span></strong></a></p>';
mm += '</div><!--/MMColumn1-->';
mm += '</div><!--/MMGrid4-->';
mm += '</div><!--/MMColumnArea-->';
mm += '</dd><!--/MMSet-->';
mm += '<dt class="MMGlobalNaviStyle"><a href="$link$">Section 5</a></dt>';
mm += '</dl>';

var __globalnavi = "";
if ($("#GlobalNaviTop").length == 1) {
	__globalnavi = "#GlobalNaviTop";
}
if ($("#GlobalNaviMenu").length == 1) {
	__globalnavi = "#GlobalNaviMenu";
}

if (__globalnavi) {
	$(__globalnavi).after(mm).find("li").each(function(i) {
		if($(this).hasClass("Current")) {
			var $this = $(".MMGlobalNaviStyle").eq(i);
			$this.addClass("Current");
			if($(this).find("strong")[0]) {
				$this.find("a").html("<strong>" + $this.text() + "</strong>");
			} else if($(this).find("em")[0]) {
				$this.find("a").html("<em>" + $this.text() + "</em>");
			}
		}
	}).parent().remove();
}